# Generated by Django 5.1.1 on 2024-09-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mon_application', '0002_alter_activity_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='duration',
        ),
    ]
