# Generated by Django 5.1.1 on 2024-09-20 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_application', '0005_activity_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='calories',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='activity',
            name='total',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
