# Generated by Django 5.1.1 on 2024-09-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_application', '0006_alter_activity_calories_alter_activity_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userobjective',
            name='objectif_jogging',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userobjective',
            name='objectif_marche',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userobjective',
            name='objectif_velo',
            field=models.FloatField(default=0),
        ),
    ]
