# Generated by Django 5.1.1 on 2024-09-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_application', '0007_alter_userobjective_objectif_jogging_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='vitesse',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
