# Generated by Django 5.1.1 on 2024-09-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_application', '0008_activity_vitesse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='vitesse',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
